In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
def conv(x,h):
  lx = len(x)
  lh = len(h)
  y = np.zeros(lx+lh-1)

  for m in range(lx):
    for n in range(lh):
      y[m+n] = y[m+n] + x[m]*h[n]
  return y
    
x = [2,0,3,-4,1]
h = [1,3,0,4,2]

y = conv(x,np.flip(h))
print(y)

z = np.correlate(x,h,'full')
print(z)


[  4.   8.   6.  10. -12.  13.  -9.  -1.   1.]
[  4   8   6  10 -12  13  -9  -1   1]


In [11]:
def crosscorr(x,h):
  lx = len(x)
  h = np.flip(h)
  lh = len(h)
  y = np.zeros(lx+lh-1)

  for m in range(lx):
    for n in range(lh):
      y[m+n] = y[m+n] + x[m]*h[n]
  return y

x = [1,2,0,3,4]
y = [3,1,2,0,-1]

rxy = crosscorr(x,y)
print(rxy)
z = np.correlate(x,y,'full')
print(z)


[-1. -2.  2.  2.  1. 12. 11. 13. 12.]
[-1 -2  2  2  1 12 11 13 12]


In [12]:
#auto-correlation
y = crosscorr(x,x)
print(y)

z = np.correlate(x,x,'full')
print(z)

[ 4. 11.  6. 14. 30. 14.  6. 11.  4.]
[ 4 11  6 14 30 14  6 11  4]
